import Image, { getImageProps } from 'next/image';
import { ArrowUpRight, Phone, Layers3, Ruler, Truck, Mail, MapPin } from 'lucide-react';
import { Navigation, ServiceLink, InquiryForm, BrandStrip, Projects, Reviews } from '@/components/interactions';
const services=[
 {title:'Krovstvo in sanacije',image:'krovstvo',text:'Od prve kritine do celovite obnove. Strešna rešitev, prilagojena vašemu domu.'},
 {title:'Tesarstvo',image:'tesarstvo',text:'Ostrešja, nadstreški in lesene konstrukcije. Naravni material, natančno izvedeni detajli.'},
 {title:'Kleparstvo',image:'kleparstvo',text:'Žlebovi, obrobe in pločevinaste kritine. Detajli, ki povežejo streho v celoto.'},
 {title:'Ravne strehe',image:'ravne-strehe',text:'Čiste linije in premišljena zaščita. Izvedba ravnih streh s sodobnimi sistemi kritja.'},
 {title:'Strešna okna Velux',image:'stresna-okna',text:'Več svetlobe pod vašo streho. Dobava in montaža oken, senčil ter dodatne opreme.'},
];
const steps=[['Prvi pogovor','Pokličite ali nam opišite|objekt in svoje želje.|Začnemo s pogovorom.'],['Prava rešitev','Skupaj razmislimo o materialih,|izvedbi in posebnostih|vašega objekta.'],['Jasen dogovor','Določimo obseg del ter|se dogovorimo o ponudbi|in poteku izvedbe.'],['Natančna izvedba','Od konstrukcije do zadnje|obrobe poskrbimo za|dogovorjeno izvedbo.']];
export default function Home(){
 const common={alt:'Ilustrativni prikaz sodobne hiše s pločevinasto streho v topli večerni svetlobi',sizes:'100vw',loading:'eager' as const,fetchPriority:'high' as const,quality:85};
 const {props:{srcSet:desktop}}=getImageProps({...common,src:'/images/hero-dom-desktop.webp',width:1536,height:1024});
 const {props:mobile}=getImageProps({...common,src:'/images/hero-dom-mobile.webp',width:1024,height:1536});
 return <><Navigation/><main id="vsebina"><section className="hero" aria-labelledby="hero-title"><div className="hero-photo"><picture><source media="(min-width: 701px)" srcSet={desktop}/><img {...mobile} alt={common.alt}/></picture></div><div className="hero-shade"/><div className="hero-shutters" aria-hidden="true"><div className="hero-shutter"/><div className="hero-shutter"/><div className="hero-shutter"/></div><div className="container hero-content"><h1 id="hero-title"><span className="hero-line"><span>Streha, ki</span></span><span className="hero-line"><span>zaokroži</span></span><span className="hero-line"><span className="hero-accent">vaš dom.</span></span></h1><div className="hero-bottom"><p>Krovstvo, tesarstvo in kleparstvo.<br/>Od prve ideje do zadnjega detajla.</p><div className="hero-actions"><a href="#povprasevanje" className="button button-bronze">Pošlji povpraševanje <ArrowUpRight size={19}/></a><a href="#projekti" className="hero-secondary">Oglejte si projekte <ArrowUpRight size={17}/></a></div></div></div><section id="zaupanje" className="trust-section" aria-label="Zakaj nam zaupati"><div className="container trust-grid"><div className="trust-year"><strong>2009</strong><span>Z vami že od leta 2009</span></div><div><Layers3/><p>Celovita izvedba<span>Krovstvo, tesarstvo in kleparstvo</span></p></div><div><Ruler/><p>Prava izbira materialov<span>Svetovanje za vaš objekt</span></p></div><div><Truck/><p>Od začetka do zaključka<span>Obnova z odvozom materiala</span></p></div></div></section></section>
<section id="storitve" className="section services-section"><div className="container"><div className="section-heading"><h2>Vse, kar potrebuje<br/><span className="muted-heading">vaša streha.</span></h2><p>Trdna konstrukcija. Prava kritina. Dovršeni detajli. Različna znanja povežemo v eno celovito rešitev.</p></div><div className="services-grid">{services.map((s,i)=><article key={s.image} className={`service-card service-card-${i}`}><div className="service-image"><Image src={`/images/${s.image}.webp`} alt={`Ilustrativni prikaz: ${s.title}`} fill sizes={i<3?'(max-width: 700px) 100vw, 33vw':'(max-width: 700px) 100vw, 50vw'}/></div><div className="service-info"><div><h3>{s.title}</h3><p>{s.text}</p></div><ServiceLink service={s.title}/></div></article>)}</div><p className="image-note">Fotografije storitev so ilustrativne. Naše izvedbe si oglejte med projekti.</p></div></section>
<section id="povprasevanje" className="inquiry-section"><div className="container inquiry-grid"><div className="inquiry-intro"><h2>Vaša ideja.<br/>Naše znanje.<br/><span className="bronze-light">Skupna rešitev.</span></h2><p>Načrtujete novo streho ali obnovo? Povejte nam, kaj potrebujete, in skupaj poiščimo pravo pot.</p><div className="inquiry-call"><p>Ali nas pokličite</p><a href="tel:+38641461732" className="large-phone"><Phone size={24}/>041 461 732</a><a className="email-link" href="mailto:strehe.jerman@gmail.com">strehe.jerman@gmail.com <ArrowUpRight size={16}/></a></div></div><InquiryForm/></div></section>
<section id="o-podjetju" className="section about-section"><div className="container about-grid"><div className="about-visual"><Image src="/images/projekt-druzenje.webp" alt="Lesena konstrukcija pri dejanski izvedbi podjetja Strehe Jerman" fill sizes="(max-width: 700px) 100vw, 48vw"/><div className="about-stamp"><strong>Znanje,<br/>ki se vidi.</strong></div></div><div className="about-copy"><h2>Za dobro streho<br/>stojijo dobri<br/><span className="muted-heading">mojstri.</span></h2><p>Smo podjetje iz Otočca. Od leta 2009 povezujemo krovska, tesarska in kleparska dela, pri novih domovih in objektih, ki potrebujejo novo poglavje.</p><p>Pomagamo pri izbiri materialov in izvedbi, ki ustreza vašemu objektu. Od lesenega ostrešja in kritine do žlebov, obrob ter strešnih oken.</p><ul className="about-points"><li><span>01</span>Različna znanja, ena celovita izvedba.</li><li><span>02</span>Rešitve za novogradnje in obnove.</li><li><span>03</span>Pozornost tudi najmanjšim detajlom.</li></ul><a className="text-link" href="#povprasevanje">Spoznajmo vaš projekt <ArrowUpRight size={20}/></a></div></div></section>
<BrandStrip/>
<section className="section process-section"><div className="container"><div className="section-heading centered"><span className="section-label">Postopek</span><h2>Od prvega klica do vaše strehe.</h2></div><ol className="steps">{steps.map(([title,text],i)=><li key={title}><div className="step-number"><span>0{i+1}</span></div><h3>{title}</h3><p>{text.split('|').map(line=><span key={line}>{line}{' '}</span>)}</p></li>)}</ol></div></section>
<section id="projekti" className="section projects-section"><div className="container"><div className="section-heading centered"><h2>Naše delo.<br/><span className="muted-heading">V pravem življenju.</span></h2><p>Vsak objekt ima svojo zgodbo.<br/>To je nekaj tistih, pri katerih smo sodelovali.</p></div><Projects/></div></section>
<Reviews/>
<section className="final-cta"><div className="container cta-inner"><div><h2>Pogovorimo se o <span>vaši strehi.</span></h2><p>Dobra streha se začne z dobrim pogovorom.</p></div><a href="#povprasevanje" className="button button-bronze">Pošlji povpraševanje <ArrowUpRight size={21}/></a></div></section></main>
<footer className="footer"><div className="container footer-top"><div className="footer-brand"><a className="footer-logo" href="#" aria-label="Strehe Jerman, na vrh"><Image src="/images/logo.webp" alt="Strehe Jerman" width={200} height={68}/></a><p>Krovstvo. Tesarstvo. Kleparstvo.<br/>Streha, ki zaokroži vaš dom.</p><a className="text-link" href="#povprasevanje">Zaupajte nam svoj projekt <ArrowUpRight size={18}/></a></div><div className="footer-column"><h3>Storitve</h3>{services.map(s=><a href={`/storitve/${s.image}`} key={s.image}>{s.title}</a>)}</div><div className="footer-column"><h3>Raziščite</h3><a href="#o-podjetju">O podjetju</a><a href="#projekti">Projekti</a><a href="#mnenja">Mnenja strank</a><a href="/pogosta-vprasanja">Pogosta vprašanja</a><a href="#povprasevanje">Kontakt</a></div><div className="footer-column"><h3>Stopimo v stik</h3><address><a href="tel:+38641461732"><Phone size={18}/>041 461 732</a><a href="mailto:strehe.jerman@gmail.com"><Mail size={18}/>strehe.jerman@gmail.com</a><a href="https://www.google.com/maps/search/?api=1&query=%C5%A0olska+cesta+21a+Oto%C4%8Dec" target="_blank" rel="noreferrer"><MapPin size={18}/>Šolska cesta 21a<br/>8222 Otočec</a></address><div className="footer-hours"><h3>Delovni čas</h3><dl><div><dt>Ponedeljek–petek</dt><dd>7.30–16.00</dd></div><div><dt>Sobota in nedelja</dt><dd>Zaprto</dd></div></dl></div></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Strehe Jerman · Aleš Jerman s.p.</span><div><a href="/zasebnost">Politika zasebnosti</a><a href="/piskotki">Piškotki</a><a href="/pravna-obvestila">Pravna obvestila</a></div><a href="#">Na vrh <ArrowUpRight size={15}/></a></div></footer></>;
}
