'use client';
import { useEffect, useRef, useState } from 'react';
import Image from 'next/image';
import * as Dialog from '@radix-ui/react-dialog';
import { motion, useReducedMotion } from 'motion/react';
import { ArrowUpRight, ArrowRight, Phone, Menu, X, ChevronDown, Star, Pause, Play, Check, ChevronLeft, ChevronRight } from 'lucide-react';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { useGSAP } from '@gsap/react';
import Lenis from 'lenis';
import { Button } from './ui/button';
gsap.registerPlugin(ScrollTrigger,useGSAP);
const servicePages=[['Krovstvo in sanacije','krovstvo'],['Tesarstvo','tesarstvo'],['Kleparstvo','kleparstvo'],['Ravne strehe','ravne-strehe'],['Strešna okna Velux','stresna-okna']];
const links=[['O podjetju','#o-podjetju'],['Projekti','#projekti'],['Mnenja','#mnenja'],['Pogosta vprašanja','/pogosta-vprasanja']] as const;
export function Navigation(){
 const [open,setOpen]=useState(false);const [servicesOpen,setServicesOpen]=useState(false);const reduced=useReducedMotion();const dropdown=useRef<HTMLDivElement>(null);
 useEffect(()=>{const close=(e:PointerEvent)=>{if(!dropdown.current?.contains(e.target as Node))setServicesOpen(false);};document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close);},[]);
 return <header className="header"><a className="brand" href="#" aria-label="Strehe Jerman, na vrh strani"><Image src="/images/logo.webp" alt="Strehe Jerman — krovstvo in kleparstvo" width={218} height={74} sizes="160px"/></a><nav className="desktop-nav" aria-label="Glavna navigacija"><div className="services-dropdown" ref={dropdown} onKeyDown={e=>{if(e.key==='Escape'){setServicesOpen(false);dropdown.current?.querySelector('button')?.focus();}}}><button aria-expanded={servicesOpen} aria-controls="service-navigation" onClick={()=>setServicesOpen(!servicesOpen)}>Storitve <ChevronDown size={16}/></button>{servicesOpen&&<div className="dropdown-panel" id="service-navigation">{servicePages.map(([name,slug])=><a href={`/storitve/${slug}`} key={slug}>{name}<ArrowUpRight size={16}/></a>)}</div>}</div>{links.map(([label,href])=><a key={href} href={href}>{label}</a>)}</nav><div className="header-actions"><a className="header-phone" href="tel:+38641461732"><Phone size={17}/>041 461 732</a><a className="button button-bronze header-contact" href="#povprasevanje">Pošlji povpraševanje <ArrowUpRight size={17}/></a></div><Dialog.Root open={open} onOpenChange={setOpen}><Dialog.Trigger className="menu-toggle" aria-label="Odpri meni"><Menu/></Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content data-lenis-prevent className="mobile-menu"><Dialog.Title className="sr-only">Navigacija</Dialog.Title><Dialog.Description className="sr-only">Povezave do razdelkov in prihodnjih podstrani</Dialog.Description><Dialog.Close className="close-button" aria-label="Zapri meni"><X/></Dialog.Close><motion.nav initial={reduced?false:{opacity:0,y:12}} animate={{opacity:1,y:0}} aria-label="Mobilna navigacija"><details><summary>Storitve <ChevronDown size={20}/></summary>{servicePages.map(([name,slug])=><a href={`/storitve/${slug}`} key={slug}>{name}</a>)}</details>{[...links,['Pošlji povpraševanje','#povprasevanje']].map(([label,href])=><a key={href} href={href} onClick={()=>setOpen(false)}>{label}<ArrowUpRight/></a>)}<a className="mobile-phone" href="tel:+38641461732"><Phone size={20}/>041 461 732</a></motion.nav></Dialog.Content></Dialog.Portal></Dialog.Root></header>;
}
export function MotionSystem({children}:{children:React.ReactNode}){
 const scope=useRef<HTMLDivElement>(null);
 useGSAP(()=>{
  const mm=gsap.matchMedia();
  mm.add('(prefers-reduced-motion: no-preference)',()=>{
   const lenis=new Lenis({anchors:{offset:-90},duration:1.05,prevent:node=>node.hasAttribute('data-lenis-prevent')});
   const tick=(time:number)=>lenis.raf(time*1000);lenis.on('scroll',ScrollTrigger.update);gsap.ticker.add(tick);gsap.ticker.lagSmoothing(0);
   ScrollTrigger.config({ignoreMobileResize:true});
   const hero=gsap.timeline({defaults:{ease:'power3.out'}});
   hero.from('.hero-shutter',{scaleY:1,duration:1.15,stagger:.1,transformOrigin:'top'},0)
       .from('.hero-photo',{scale:1.06,duration:1.9,ease:'power2.out'},0)
       .from('.hero-line > span',{yPercent:105,duration:1,stagger:.1},.2)
       .from('.hero-bottom',{y:18,opacity:0,duration:.8},.65);
   const scrollMedia=gsap.matchMedia();
   scrollMedia.add('(min-width: 769px)',()=>gsap.to('.hero-photo',{yPercent:12,ease:'none',scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom top',scrub:true}}));
   document.fonts.ready.then(()=>ScrollTrigger.refresh());
   return ()=>{scrollMedia.revert();gsap.ticker.remove(tick);lenis.destroy();};
  });
  return ()=>mm.revert();
 },{scope});
 return <div ref={scope}>{children}</div>;
}
const options=['Krovstvo in sanacije','Tesarstvo','Kleparstvo','Ravne strehe','Strešna okna Velux'];
export function ServiceLink({service}:{service:string}){return <a className="service-link" href="#povprasevanje" onClick={()=>window.dispatchEvent(new CustomEvent('select-service',{detail:service}))} aria-label={`Povprašajte za storitev: ${service}`}><ArrowUpRight size={25}/></a>;}
const schema=z.object({name:z.string().trim().min(2,'Vpišite svoje ime.'),phone:z.string().trim().regex(/^[+\d\s()/.-]{6,20}$/,'Vpišite veljavno telefonsko številko.'),service:z.string().min(1,'Izberite storitev.'),message:z.string().trim()});
type Fields=z.infer<typeof schema>;
export function InquiryForm(){
 const [sent,setSent]=useState(false);const {register,handleSubmit,setValue,formState:{errors}}=useForm<Fields>({resolver:zodResolver(schema),defaultValues:{name:'',phone:'',service:'',message:''}});
 useEffect(()=>{const select=(event:Event)=>{setSent(false);setValue('service',(event as CustomEvent<string>).detail,{shouldValidate:true});};window.addEventListener('select-service',select);return()=>window.removeEventListener('select-service',select);},[setValue]);
 return <form className="inquiry-form" noValidate onSubmit={handleSubmit(()=>setSent(true))}><div className="form-row"><label htmlFor="name">Ime in priimek<input id="name" autoComplete="name" {...register('name')} aria-invalid={!!errors.name} aria-describedby={errors.name?'name-error':undefined} placeholder=""/>{errors.name&&<span className="field-error" id="name-error">{errors.name.message}</span>}</label><label htmlFor="phone">Telefon<input id="phone" type="tel" autoComplete="tel" {...register('phone')} aria-invalid={!!errors.phone} aria-describedby={errors.phone?'phone-error':undefined} placeholder=""/>{errors.phone&&<span className="field-error" id="phone-error">{errors.phone.message}</span>}</label></div><div className="form-row"><label htmlFor="service">Vrsta storitve<select id="service" {...register('service')} aria-invalid={!!errors.service} aria-describedby={errors.service?'service-error':undefined}><option value="">Izberite storitev</option>{options.map(o=><option key={o}>{o}</option>)}</select>{errors.service&&<span className="field-error" id="service-error">{errors.service.message}</span>}</label><label htmlFor="message">Sporočilo <span className="optional">(neobvezno)</span><textarea id="message" rows={3} {...register('message')} aria-invalid={!!errors.message} aria-describedby={errors.message?'message-error':undefined} placeholder="Lokacija, obnova ali novogradnja, vaše želje …"/>{errors.message&&<span className="field-error" id="message-error">{errors.message.message}</span>}</label></div><div className="form-bottom"><span>Predstavitveni obrazec.<br/>Podatki se ne pošiljajo ali shranjujejo.</span><Button type="submit">Pošlji povpraševanje <ArrowUpRight size={19}/></Button></div><div role="status" aria-live="polite">{sent&&<p className="form-success"><Check size={20}/>Demo: sporočilo ni bilo poslano. Za stik pokličite 041 461 732.</p>}</div></form>;
}
const brands=['Bramac','Tondach','Creaton','Tegola','Decra','Trimo'];
export function BrandStrip(){
 const ref=useRef<HTMLDivElement>(null);
 useEffect(()=>{const el=ref.current;if(!el)return;let visible=false;const sync=()=>el.dataset.running=String(visible&&!document.hidden);const observer=new IntersectionObserver(([entry])=>{visible=entry.isIntersecting;sync();});observer.observe(el);document.addEventListener('visibilitychange',sync);return()=>{observer.disconnect();document.removeEventListener('visibilitychange',sync);};},[]);
 return <section className="brands-section" aria-label="Znamke materialov"><div className="container brands-heading"><h2>Kakovost se začne<br/>s <span className="muted-heading">pravimi materiali.</span></h2></div><div ref={ref} className="brand-window" tabIndex={0} aria-label="Logotipi proizvajalcev. Premikanje se ustavi ob fokusu ali s kazalcem."><div className="brand-track">{[0,1].map(copy=><div className="brand-group" key={copy} aria-hidden={copy===1}>{brands.map(brand=><div className={`brand-slot brand-${brand.toLowerCase()}`} key={brand}><Image src={`/images/${brand.toLowerCase()}.webp`} alt={brand} width={200} height={100} sizes="200px" loading="eager" className="brand-logo"/></div>)}</div>)}</div></div></section>;
}
const projects=[{image:'projekt-skedenj',title:'Nova zgodba starega skednja',category:'Obnova skednja',description:'Ohranjen značaj. Nova konstrukcija.'},{image:'projekt-hlev',title:'Prostor za konje',category:'Postavitev hleva za konje',description:'Lesena konstrukcija od temeljev do strehe.'},{image:'projekt-druzenje',title:'Pod streho, na prostem',category:'Postavitev prostora za druženje',description:'Prostor, ki povezuje dom in vrt.'}];
export function Projects(){
 const [selected,setSelected]=useState<number|null>(null);const index=selected??0;
 return <><div className="projects-grid">{projects.map((p,i)=><button key={p.image} className={`project project-${i}`} onClick={()=>setSelected(i)} title={`Odpri fotografijo: ${p.category}`}><div className="project-image"><Image src={`/images/${p.image}.webp`} alt={p.category+' — dejanska izvedba Strehe Jerman'} fill sizes={i===0?'(max-width: 700px) 100vw, 55vw':'(max-width: 700px) 100vw, 35vw'}/><span className="project-open"><ArrowUpRight size={25}/></span></div><div className="project-caption"><div><h3>{p.title}</h3><p>{p.category}</p></div><span>0{i+1}</span></div></button>)}</div><Dialog.Root open={selected!==null} onOpenChange={open=>{if(!open)setSelected(null);}}><Dialog.Portal><Dialog.Overlay className="dialog-overlay gallery-overlay"/><Dialog.Content data-lenis-prevent className="gallery" onKeyDown={event=>{if(event.key==='ArrowRight')setSelected((index+1)%projects.length);if(event.key==='ArrowLeft')setSelected((index+projects.length-1)%projects.length);}}><Dialog.Title className="gallery-title">{projects[index].category}</Dialog.Title><Dialog.Description className="sr-only">Fotografija izvedbe podjetja Strehe Jerman. Za menjavo uporabite puščice.</Dialog.Description><Dialog.Close className="close-button" aria-label="Zapri galerijo"><X/></Dialog.Close><div className="gallery-image"><Image src={`/images/${projects[index].image}.webp`} alt={projects[index].category} fill sizes="90vw"/></div><div className="gallery-controls"><button className="icon-button" aria-label="Prejšnji projekt" onClick={()=>setSelected((index+projects.length-1)%projects.length)}><ChevronLeft/></button><span>{index+1} / {projects.length}</span><button className="icon-button" aria-label="Naslednji projekt" onClick={()=>setSelected((index+1)%projects.length)}><ChevronRight/></button></div></Dialog.Content></Dialog.Portal></Dialog.Root></>;
}
export function TextArrow(){return <ArrowRight size={18}/>;}

const reviews=[['Obnova strehe','Kljub zamiku zaradi vremena je bila stranka z novo podobo strehe izjemno zadovoljna.'],['Izdelava nadstreška','Ob številnih idejah in omejenem prostoru je Alešev predlog izpolnil pričakovanja stranke.'],['Obnova kozolca','Stranka je pri obnovi starega kozolca posebej izpostavila ohranjen značaj, strokovnost in sodelovanje ekipe.']];
export function Reviews(){
 const [active,setActive]=useState(0);const [paused,setPaused]=useState(false);const [interacting,setInteracting]=useState(false);const [visible,setVisible]=useState(false);const ref=useRef<HTMLElement>(null);const reduced=useReducedMotion();
 useEffect(()=>{const el=ref.current;if(!el)return;const observer=new IntersectionObserver(([entry])=>setVisible(entry.isIntersecting),{threshold:.3});observer.observe(el);return()=>observer.disconnect();},[]);
 useEffect(()=>{if(paused||interacting||!visible||reduced)return;const timer=window.setInterval(()=>{if(!document.hidden)setActive(i=>(i+1)%reviews.length);},2000);return()=>window.clearInterval(timer);},[paused,interacting,visible,reduced]);
 return <section ref={ref} id="mnenja" className="section reviews-section" onMouseEnter={()=>setInteracting(true)} onMouseLeave={()=>setInteracting(false)} onFocusCapture={()=>setInteracting(true)} onBlurCapture={e=>{if(!e.currentTarget.contains(e.relatedTarget))setInteracting(false);}}><div className="container"><div className="section-heading centered"><span className="section-label">Mnenja strank</span><h2>Največ povedo tisti, ki nam zaupajo.</h2></div><div className="review-carousel"><button className="icon-button review-prev" aria-label="Prejšnje mnenje" onClick={()=>setActive((active+reviews.length-1)%reviews.length)}><ChevronLeft size={21}/></button><article className="review-card" aria-live={paused||interacting?"polite":"off"}><div className="review-rating-preview"><div className="review-stars" aria-hidden="true">{[0,1,2,3,4].map(i=><Star key={i} size={19} fill="currentColor"/>)}</div><small>Prikaz ocene za demo · ocena ni potrjena</small></div><p>{reviews[active][1]}</p><div><span/>{reviews[active][0]}</div></article><button className="icon-button review-next" aria-label="Naslednje mnenje" onClick={()=>setActive((active+1)%reviews.length)}><ChevronRight size={21}/></button></div><div className="review-dots"><button className="review-autoplay" aria-label={paused?"Začni menjavanje mnenj":"Ustavi menjavanje mnenj"} aria-pressed={paused} onClick={()=>setPaused(!paused)}>{paused?<Play size={15}/>:<Pause size={15}/>}</button>{reviews.map(([title],i)=><button key={title} aria-label={`Prikaži mnenje: ${title}`} aria-pressed={active===i} onClick={()=>setActive(i)}/>)}</div><a className="review-source-button" href="https://www.strehe-jerman.si/" target="_blank" rel="noreferrer">Mnenja strank <ArrowUpRight size={17}/></a><p className="image-note">Povzetki izjav strank z obstoječe spletne strani Strehe Jerman.</p></div></section>;}
